### ISSUE TITLE
io.github.libsdl4j not found

### ISSUE THREAD

**Issue by mingtianshi** [FMudanyali/DanmakuProject#1]

**Comment by mingtianshi** [comment]
This exception occurs when using the jar package
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'SDL2_mixer':
dlopen(libSDL2_mixer.dylib, 9): image not found
dlopen(libSDL2_mixer.dylib, 9): image not found
dlopen(/Users/ni/Library/Frameworks/SDL2_mixer.framework/SDL2_mixer, 9): image not found
dlopen(/Library/Frameworks/SDL2_mixer.framework/SDL2_mixer, 9): image not found
dlopen(/System/Library/Frameworks/SDL2_mixer.framework/SDL2_mixer, 9): image not found
Native library (darwin-x86-64/libSDL2_mixer.dylib) not found in resource path ([file:/Volumes/application/danmaku/target/DanmakuProject/DanmakuProject-0.0.1.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Native.register(Native.java:1746)
	at com.sun.jna.Native.register(Native.java:1467)
	at com.fmudanyali.Audio.<clinit>(Audio.java:74)
	at com.fmudanyali.Main.main(Main.java:50)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libSDL2_mixer.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 5 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libSDL2_mixer.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 5 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Users/ni/Library/Frameworks/SDL2_mixer.framework/SDL2_mixer, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 5 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/Library/Frameworks/SDL2_mixer.framework/SDL2_mixer, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 5 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(/System/Library/Frameworks/SDL2_mixer.framework/SDL2_mixer, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:248)
		... 5 more
	Suppressed: java.io.IOException: Native library (darwin-x86-64/libSDL2_mixer.dylib) not found in resource path ([file:/Volumes/application/danmaku/target/DanmakuProject/DanmakuProject-0.0.1.jar])
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1119)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:275)
		... 5 more
```

**Comment by FMudanyali** [comment]
Hi, if you have homebrew, can you try installing "sdl2_mixer" package or try installing it from https://www.libsdl.org/projects/SDL_mixer/ to see if it works?
